### ISSUE TITLE
Error AD0001: Could not load file or assembly 'NetFabric.CodeAnalysis, Version=4.1.0.0'

### ISSUE THREAD

**Issue by robinvanpoppel** [NetFabric/NetFabric.Hyperlinq.Analyzer#73]
When upgrading from 2.0.4 to 2.1.0 my builds start failing with multiple occurences of the following error message:
`CSC : error AD0001: Analyzer 'NetFabric.Hyperlinq.Analyzer.AssignmentBoxingAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'NetFabric.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'.
`. Most of the projects are targeting net48.

**Comment by xtqqczze** [comment]
@robinvanpoppel Could you try adding a package reference to [`NetFabric.CodeAnalysis`](https://www.nuget.org/packages/NetFabric.CodeAnalysis) and report whether the error still occurs?

Using .NET CLI, you can achieve this with the following command line:
>  `dotnet add package NetFabric.CodeAnalysis --version 4.1.0`

**Comment by xtqqczze** [comment]
@aalmada Looks like the NuGet package is missing a dependency on `NetFabric.CodeAnalysis`.

**Comment by robinvanpoppel** [comment]
Is a fix planned? Or can I help out by supplying a PR?

**Comment by robinvanpoppel** [comment]
I did not try that because you mentioned the nuget package was missing a dependency. I can of course try it as a workaround but since `NetFabric.CodeAnalysis` should be a dependency of the analyzers I am hesitant to have a direct dependency myself.

**Comment by DavidTCarpenters** [comment]
+1 Adding a package reference to NetFabric.CodeAnalysis does not resolve the error, had to roll back to v2.0.4 to use the analyzer

**Comment by DavidTCarpenters** [comment]
I did yeah

**Comment by xtqqczze** [comment]
cc: @aalmada

**Comment by aalmada** [comment]
Hi all,
Sorry but I've been away from all my open-source projects.
NetFabric.CodeAnalysis contains code that can be useful for other developers and, having it as a separate projects, makes it more likely for others to contribute.
Unfortunately, dependencies in analyzers have been a mystery to me. I can't find documentation about it. The analyzer is placed in folder where there is no dependency versioning.
I first tried merging the assemblies to avoid this issue. Unfortunately, but both projects ILMerge and ILRepack are no longer maintained and I've been running into build issues.
Does any of you have a suggestion on how to solve dependencies for analyzers?

**Comment by aalmada** [comment]
Hello,

I want to express my gratitude to @robinvanpoppel for contributing to pull request #76. This should hopefully resolve the dependency issue. 

I've released a new version, available both on [NuGet](https://www.nuget.org/packages/NetFabric.Hyperlinq.Analyzer/2.2.0) and the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=NetFabric.NetFabricHyperlinqAnalyzer).

During my sabbatical, I plan to allocate some of my time to enhance and expand the rules within this analyzer. Additionally, I've been sharing articles related to this on my LinkedIn profile: [LinkedIn Articles](https://www.linkedin.com/in/antaoalmada/recent-activity/articles/).

I'm eager to hear about your experiences with the analyzer. For now, I'll keep this issue open. Please share your feedback.

**Comment by DavidTCarpenters** [comment]
Hi all,

I've pulled the latest and I'm afraid the issue still appears to be present, with the following warning displayed:

warning AD0001: Analyzer 'NetFabric.Hyperlinq.Analyzer.NonDisposableEnumeratorAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Could not load type 'NetFabric.CodeAnalysis.Errors' from assembly 'NetFabric.CodeAnalysis, Version=5.1.0.0, Culture=neutral, PublicKeyToken=null'.'.

**Comment by aalmada** [comment]
@DavidTCarpenters Thank you for the feedback

I'm going to give assembly merging another shot. Here's a compilation of assembly merger options I've come across:

1. [ILMerge](https://github.com/dotnet/ILMerge)
2. [ILRepack](https://github.com/gluck/il-repack) (formerly used in conjunction with [ILRepack.MSBuild.Task](https://github.com/peters/ILRepack.MSBuild.Task), but can also be employed with [ILRepack.Lib.MSBuild.Task](https://github.com/ravibpatel/ILRepack.Lib.MSBuild.Task))
3. [dnMerge](https://github.com/CCob/dnMerge)
4. [Costura](https://github.com/Fody/Costura) (note: patronage required for access)
5. [ILLink](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming)

**Comment by aalmada** [comment]
In attempt #77, I experimented with dnMerge but encountered an issue where the resulting assembly still had dependencies on NetFabric.CodeAnalysis.

Subsequently, in attempt #78, I employed ILRepack.MSBuild.Task, which functioned as expected on my local environment. However, when integrated with GitHub actions, it failed to build successfully. I had previously reported this issue in the following GitHub repository: [gluck/il-repack#273](https://github.com/gluck/il-repack/issues/273).

**Comment by aalmada** [comment]
ILLink (trimming) appears to be the current "official" solution, with other alternatives either abandoned or in maintenance mode. I'm inclined to investigate this new solution further.

**Comment by xtqqczze** [comment]
@aalmada Unfortunately trimming doesn't appear to work for projects targeting .NET Standard.

Additionally, starting in the .NET 8 SDK, trimming is unsupported for any version of .NET Standard or .NET Framework.

https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/trimming-unsupported-targetframework

**Comment by aalmada** [comment]
@xtqqczze Appreciate it! It's quite unfortunate, though, as I'm encountering problems with all the other options.

**Comment by xtqqczze** [comment]
@aalmada Does anything like this work:

`<PackageReference Include="NetFabric.CodeAnalysis" Version="4.1.0" PrivateAssets="all" Pack="true" />`

See https://til.cazzulino.com/msbuild/how-to-include-package-reference-files-in-your-nuget-package

**Comment by aalmada** [comment]
@xtqqczze, I'm grateful for your valuable suggestion!

In the context of NuGet packages, it's a common practice for them to extract their dependencies into the same directory as the executable. When it comes to analyzers, the executable in question is Roslyn, and it needs to locate the required assemblies. Inside the .csproj file, there is a target named `_AddAnalyzersToOutput` responsible for copying analyzer assemblies into the "analyzers/dotnet/cs" folder.

The pull request (PR) submitted by @robinvanpoppel aimed to install the dependency into this same folder. However, a significant concern arises in this scenario - there's no versioning for these assemblies. What if another analyzer relies on the same assembly but with a different version? That's why I created the NetFabric.CodeAnalysis package, designed to be reusable by other analyzers or source generators.

The solution to this versioning challenge comes in two parts. One approach involves copying the source code into the analyzer itself, although I'm currently hesitant to pursue this option. The alternative, which is more ideal, is to merge the assemblies. This would make the dependencies disappear while still maintaining the independence of the projects. The success of the second solution largely depends on the effectiveness of at least one of the assembly mergers.

At present, ILRepack is functioning smoothly on my local setup, and I can release a new package. However, this results in the loss of GitHub CI. I remain hopeful that either ILRepack or dnMerge will ultimately resolve this issue.

**Comment by aalmada** [comment]
I have just released version 2.3.0, and I genuinely hope that this resolves the problem. I deeply apologize for any inconvenience this may have caused.

**Comment by DavidTCarpenters** [comment]
Hi Antão, 

No need to apologise! Thank you for all of your work on this.

I have managed to get this to build locally and produce a package that I can reference in another project without using ILRepack. I'll fork the repo and submit a PR so that you can review, maybe this helps. I'll bump the version to 2.3.1

**Comment by DavidTCarpenters** [comment]
This really does feel like a dark art though the whole nuget distribution of analysers with dependencies.

**Comment by DavidTCarpenters** [comment]
PR is here https://github.com/NetFabric/NetFabric.Hyperlinq.Analyzer/pull/80

**Comment by ZzZombo** [comment]
More than a year later I've come because I'm bitten by this issue. Is there still no remedy?
